### PR TITLE
on some days the wrong commics have been shown, fixes #51

### LINKED ISSUE #51: Wrong comic displayed
For some dates the wrong comic loads consistently. The displayed comic appears to be a duplicate of a recent past comic. For example, The comic displayed for May 7, 2005 is the one from May 2, 2005. (May 3-5 also display this comic). The image loaded by "Open in Browser" is the same incorrect comic. I suspect this occurs elsewhere as well, because I've had comics appear repeatedly several times.

App version: 4.5

### PR DESCRIPTION
**Pull request by 3DES**
Reason was that some tags seem to be not updated all days, so more responsible tags have been used for title and ULR parsing now.

### CODE REVIEW

File: src/main/java/com/mareksebera/simpledilbert/utilities/FindUrls.java [hunk 1]
```diff
@@ -51,13 +52,14 @@ private FindUrls() {
                 if (!scan.hasNextLine()) break;
 
                 String line = scan.nextLine();
-                if (line.contains("twitter:image")) {
+
+                if (line.contains("data-image")) {
                     Matcher m = url_match_pattern.matcher(line);
                     if (m.matches()) {
-                        foundUrl = m.group(1);
+                        foundUrl = "http:" + m.group(1);
```
Comment (smarek) [inline src/main/java/com/mareksebera/simpledilbert/utilities/FindUrls.java]: Please https :)

Comment (smarek) [reply src/main/java/com/mareksebera/simpledilbert/utilities/FindUrls.java]: Otherwise it's good to go, great work, thank you!
